### ISSUE TITLE
FR: Sync Annotations

### ISSUE THREAD

**Issue by ryanwwest** [MrLokans/MoonReader_tools#16]
It would be nice to use this to get Highlight and Note annotations from books with this tool, in some consumable format like JSON (maybe Markdown as well). Ideally it would be even nicer to have a way to both _fetch_ this data and _update_ it, to allow for two-way syncing of annotation updates (and progress updates, while we're at it) between Moon+Reader and some external app that can use this as an intermediary library.

**Comment by sirpat1366** [comment]
I agree with an earlier comment about the lack of documentation.  I've gone through the steps necessary to obtain a DropBox token and made sure the "allow meta data & content data" permissions were set and clicked the tiny 'submit' button.  I then re-generated the token.

Making the call:
moon_tools --dropbox-token <my token> --output-file <my filepath>

Resulting error:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Scripts\moon_tools.exe\__main__.py", line 4, in <module>
    from moonreader_tools.main import main
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\moonreader_tools\main.py", line 10, in <module>
    import dropbox
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\dropbox\__init__.py", line 3, in <module>
    from dropbox.dropbox_client import (  # noqa: F401 # pylint: disable=unused-import
        __version__, Dropbox, DropboxTeam, create_session
    )
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\dropbox\dropbox_client.py", line 43, in <module>
    from dropbox.session import (
    ...<8 lines>...
    )
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\dropbox\session.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
