### ISSUE TITLE
get_books method shoud log errors instead of stopping program execution

### ISSUE THREAD

**Issue by MrLokans** [MrLokans/MoonReader_tools#5]
ERROR:root:Exception occured when creating book object.
Traceback (most recent call last):
  File "/home/user/venvs/personalsite/lib/python3.5/site-packages/moonreader_tools/handlers/dropbox.py", line 50, in get_books
    book = Book.from_fobj_dict(book_dict)
  File "/home/user/venvs/personalsite/lib/python3.5/site-packages/moonreader_tools/books.py", line 97, in from_fobj_dict
    book_ext = cls._get_book_type(fname)
  File "/home/user/venvs/personalsite/lib/python3.5/site-packages/moonreader_tools/books.py", line 130, in _get_book_type
    raise BookTypeError(err_msg.format(book_type, filename))
moonreader_tools.books.BookTypeError: Unknown file format: Moon+/Cache/9261 in file /Books/.Moon+/Cache/9261.po

**Comment by MrLokans** [comment]
Error already does not stop execution flow, it only logs down the exception
